AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  function1A17E8AF:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function1A17E8AF
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: runReport
      CodeUri: src/runReport
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaENIManagementAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Events:
        timer53283B9:
          Type: Schedule
          Properties:
            Schedule: rate(29 minutes)
      VpcConfig:
        SecurityGroupIds:
          - !If
            - virtualNetwork8A82F11UseExistingResource
            - !GetAtt virtualNetwork8A82F11ExistingResource.DefaultSecurityGroup
            - !GetAtt virtualNetwork8A82F11.DefaultSecurityGroup
        SubnetIds:
          - !If
            - virtualNetwork8A82F11UseExistingResource
            - !GetAtt virtualNetwork8A82F11ExistingResource.PrivateSubnet1
            - !Ref virtualNetwork8A82F11PrivateSubnet1
          - !If
            - virtualNetwork8A82F11UseExistingResource
            - !GetAtt virtualNetwork8A82F11ExistingResource.PrivateSubnet2
            - !Ref virtualNetwork8A82F11PrivateSubnet2
      Environment:
        Variables:
          DB_INSTANCE: !If
            - database25FDDF06UseExistingResource
            - !Ref database25FDDF06ExistingResource
            - !Ref database25FDDF06
          DB_ADDRESS: !If
            - database25FDDF06UseExistingResource
            - !GetAtt database25FDDF06ExistingResource.Endpoint.Address
            - !GetAtt database25FDDF06.Endpoint.Address
          DB_PORT: !If
            - database25FDDF06UseExistingResource
            - !GetAtt database25FDDF06ExistingResource.Endpoint.Port
            - !GetAtt database25FDDF06.Endpoint.Port
          DB_ARN: !If
            - database25FDDF06UseExistingResource
            - !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${database25FDDF06ExistingResource}
            - !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${database25FDDF06}
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
    Metadata:
      StackeryName: runReport
  virtualNetwork8A82F11:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName}
            - ResourceName: virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 0
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 1
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 1
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 2
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnet1:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 2
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnet 1
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnet2:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 3
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnet 2
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1NatGatewayEIP:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1NatGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt virtualNetwork8A82F11PrivateSubnet1NatGatewayEIP.AllocationId
      SubnetId: !Ref virtualNetwork8A82F11PublicSubnet1
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1RouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 1 Route Table
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1NatGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref virtualNetwork8A82F11PrivateSubnet1NatGateway
      RouteTableId: !Ref virtualNetwork8A82F11PrivateSubnet1RouteTable
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet1RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork8A82F11PrivateSubnet1RouteTable
      SubnetId: !Ref virtualNetwork8A82F11PrivateSubnet1
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2NatGatewayEIP:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2NatGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt virtualNetwork8A82F11PrivateSubnet2NatGatewayEIP.AllocationId
      SubnetId: !Ref virtualNetwork8A82F11PublicSubnet2
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2RouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 2 Route Table
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2NatGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref virtualNetwork8A82F11PrivateSubnet2NatGateway
      RouteTableId: !Ref virtualNetwork8A82F11PrivateSubnet2RouteTable
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PrivateSubnet2RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork8A82F11PrivateSubnet2RouteTable
      SubnetId: !Ref virtualNetwork8A82F11PrivateSubnet2
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnetsInternetGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnets Internet Gateway
            - ResourceName: virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnetsInternetGatewayAttachment:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref virtualNetwork8A82F11PublicSubnetsInternetGateway
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnetsRouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnets Route Table
            - ResourceName: virtualNetwork8A82F11
      VpcId: !Ref virtualNetwork8A82F11
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnetsInternetGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref virtualNetwork8A82F11PublicSubnetsInternetGateway
      RouteTableId: !Ref virtualNetwork8A82F11PublicSubnetsRouteTable
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnet1RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork8A82F11PublicSubnetsRouteTable
      SubnetId: !Ref virtualNetwork8A82F11PublicSubnet1
    Condition: virtualNetwork8A82F11CreateNewResource
  virtualNetwork8A82F11PublicSubnet2RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork8A82F11PublicSubnetsRouteTable
      SubnetId: !Ref virtualNetwork8A82F11PublicSubnet2
    Condition: virtualNetwork8A82F11CreateNewResource
  database25FDDF06:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: '0'
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref database25FDDF06SubnetGroup
      Engine: mariadb
      EngineVersion: '10.2'
      MasterUsername: root
      MasterUserPassword: ''
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName}
            - ResourceName: database25FDDF06
      VPCSecurityGroups:
        - !Ref database25FDDF06SecurityGroup
    Condition: database25FDDF06CreateNewResource
  database25FDDF06SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Subnets
        - ResourceName: database25FDDF06
      SubnetIds:
        - !If
          - virtualNetwork8A82F11UseExistingResource
          - !GetAtt virtualNetwork8A82F11ExistingResource.PrivateSubnet1
          - !Ref virtualNetwork8A82F11PrivateSubnet1
        - !If
          - virtualNetwork8A82F11UseExistingResource
          - !GetAtt virtualNetwork8A82F11ExistingResource.PrivateSubnet2
          - !Ref virtualNetwork8A82F11PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Subnets
            - ResourceName: database25FDDF06
    Condition: database25FDDF06CreateNewResource
  database25FDDF06SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database Security Group
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Security Group
            - ResourceName: database25FDDF06
      VpcId: !If
        - virtualNetwork8A82F11UseExistingResource
        - !Ref virtualNetwork8A82F11ExistingResource
        - !Ref virtualNetwork8A82F11
    Condition: database25FDDF06CreateNewResource
  database25FDDF06ExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: database
      Data: !Ref EnvConfigDBARNAsString
    Condition: database25FDDF06UseExistingResource
  virtualNetwork8A82F11ExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: virtualNetwork
      Data: !Ref EnvConfigVPCConfigAsString
    Condition: virtualNetwork8A82F11UseExistingResource
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfigDBARNAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/DB_ARN
  EnvConfigVPCConfigAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/VPC_Config
Conditions:
  database25FDDF06CreateNewResource: !Equals
    - 'false'
    - !Ref EnvConfigDBARNAsString
  database25FDDF06UseExistingResource: !Not
    - Condition: database25FDDF06CreateNewResource
  virtualNetwork8A82F11CreateNewResource: !Equals
    - 'false'
    - !Ref EnvConfigVPCConfigAsString
  virtualNetwork8A82F11UseExistingResource: !Not
    - Condition: virtualNetwork8A82F11CreateNewResource
Metadata:
  EnvConfigParameters:
    EnvConfigDBARNAsString: DB_ARN
    EnvConfigVPCConfigAsString: VPC_Config