AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  functionF582E1C5:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-functionF582E1C5
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: myFunction
      CodeUri: src/myCode2
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaENIManagementAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Events:
        timer6C97BED9:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
      VpcConfig:
        SecurityGroupIds:
          - !If
            - virtualNetwork88E7FFCCUseExistingResource
            - !GetAtt virtualNetwork88E7FFCCExistingResource.DefaultSecurityGroup
            - !GetAtt virtualNetwork88E7FFCC.DefaultSecurityGroup
        SubnetIds:
          - !If
            - virtualNetwork88E7FFCCUseExistingResource
            - !GetAtt virtualNetwork88E7FFCCExistingResource.PrivateSubnet1
            - !Ref virtualNetwork88E7FFCCPrivateSubnet1
          - !If
            - virtualNetwork88E7FFCCUseExistingResource
            - !GetAtt virtualNetwork88E7FFCCExistingResource.PrivateSubnet2
            - !Ref virtualNetwork88E7FFCCPrivateSubnet2
      Environment:
        Variables:
          DB_INSTANCE: !If
            - databaseADBEA118UseExistingResource
            - !Ref databaseADBEA118ExistingResource
            - !Ref databaseADBEA118
          DB_ADDRESS: !If
            - databaseADBEA118UseExistingResource
            - !GetAtt databaseADBEA118ExistingResource.Endpoint.Address
            - !GetAtt databaseADBEA118.Endpoint.Address
          DB_PORT: !If
            - databaseADBEA118UseExistingResource
            - !GetAtt databaseADBEA118ExistingResource.Endpoint.Port
            - !GetAtt databaseADBEA118.Endpoint.Port
          DB_ARN_FOO: !If
            - databaseADBEA118UseExistingResource
            - !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${databaseADBEA118ExistingResource}
            - !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${databaseADBEA118}
          MyVar: '1'
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
    Metadata:
      StackeryName: myFunction
  virtualNetwork88E7FFCC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName}
            - ResourceName: virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 0
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 1
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 1
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 2
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnet1:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 2
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnet 1
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnet2:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 3
        - !Cidr
          - 10.0.0.0/16
          - 4
          - 14
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnet 2
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1NatGatewayEIP:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1NatGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt virtualNetwork88E7FFCCPrivateSubnet1NatGatewayEIP.AllocationId
      SubnetId: !Ref virtualNetwork88E7FFCCPublicSubnet1
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1RouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 1 Route Table
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1NatGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref virtualNetwork88E7FFCCPrivateSubnet1NatGateway
      RouteTableId: !Ref virtualNetwork88E7FFCCPrivateSubnet1RouteTable
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet1RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork88E7FFCCPrivateSubnet1RouteTable
      SubnetId: !Ref virtualNetwork88E7FFCCPrivateSubnet1
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2NatGatewayEIP:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2NatGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt virtualNetwork88E7FFCCPrivateSubnet2NatGatewayEIP.AllocationId
      SubnetId: !Ref virtualNetwork88E7FFCCPublicSubnet2
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2RouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Private Subnet 2 Route Table
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2NatGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref virtualNetwork88E7FFCCPrivateSubnet2NatGateway
      RouteTableId: !Ref virtualNetwork88E7FFCCPrivateSubnet2RouteTable
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPrivateSubnet2RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork88E7FFCCPrivateSubnet2RouteTable
      SubnetId: !Ref virtualNetwork88E7FFCCPrivateSubnet2
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnetsInternetGateway:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnets Internet Gateway
            - ResourceName: virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnetsInternetGatewayAttachment:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref virtualNetwork88E7FFCCPublicSubnetsInternetGateway
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnetsRouteTable:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Virtual Network ${ResourceName} Public Subnets Route Table
            - ResourceName: virtualNetwork88E7FFCC
      VpcId: !Ref virtualNetwork88E7FFCC
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnetsInternetGatewayRoute:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref virtualNetwork88E7FFCCPublicSubnetsInternetGateway
      RouteTableId: !Ref virtualNetwork88E7FFCCPublicSubnetsRouteTable
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnet1RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork88E7FFCCPublicSubnetsRouteTable
      SubnetId: !Ref virtualNetwork88E7FFCCPublicSubnet1
    Condition: virtualNetwork88E7FFCCCreateNewResource
  virtualNetwork88E7FFCCPublicSubnet2RouteTableAssociation:
    Metadata:
      StackeryManaged: true
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref virtualNetwork88E7FFCCPublicSubnetsRouteTable
      SubnetId: !Ref virtualNetwork88E7FFCCPublicSubnet2
    Condition: virtualNetwork88E7FFCCCreateNewResource
  databaseADBEA118:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: '0'
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref databaseADBEA118SubnetGroup
      Engine: mariadb
      EngineVersion: '10.2'
      MasterUsername: root
      MasterUserPassword: ''
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName}
            - ResourceName: databaseADBEA118
      VPCSecurityGroups:
        - !Ref databaseADBEA118SecurityGroup
    Condition: databaseADBEA118CreateNewResource
  databaseADBEA118SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Subnets
        - ResourceName: databaseADBEA118
      SubnetIds:
        - !If
          - virtualNetwork88E7FFCCUseExistingResource
          - !GetAtt virtualNetwork88E7FFCCExistingResource.PrivateSubnet1
          - !Ref virtualNetwork88E7FFCCPrivateSubnet1
        - !If
          - virtualNetwork88E7FFCCUseExistingResource
          - !GetAtt virtualNetwork88E7FFCCExistingResource.PrivateSubnet2
          - !Ref virtualNetwork88E7FFCCPrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Subnets
            - ResourceName: databaseADBEA118
    Condition: databaseADBEA118CreateNewResource
  databaseADBEA118SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database Security Group
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306
      Tags:
        - Key: Name
          Value: !Sub
            - Stack ${StackTagName} Environment ${EnvironmentTagName} Database ${ResourceName} VPC Security Group
            - ResourceName: databaseADBEA118
      VpcId: !If
        - virtualNetwork88E7FFCCUseExistingResource
        - !Ref virtualNetwork88E7FFCCExistingResource
        - !Ref virtualNetwork88E7FFCC
    Condition: databaseADBEA118CreateNewResource
  virtualNetwork88E7FFCCExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: virtualNetwork
      Data: !Ref EnvConfigVPCConfigAsString
    Condition: virtualNetwork88E7FFCCUseExistingResource
  databaseADBEA118ExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: database
      Data: !Ref EnvConfigDBARNAsString
    Condition: databaseADBEA118UseExistingResource
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfigVPCConfigAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/VPC_Config
  EnvConfigDBARNAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/DB_ARN
Conditions:
  virtualNetwork88E7FFCCCreateNewResource: !Equals
    - 'false'
    - !Ref EnvConfigVPCConfigAsString
  virtualNetwork88E7FFCCUseExistingResource: !Not
    - Condition: virtualNetwork88E7FFCCCreateNewResource
  databaseADBEA118CreateNewResource: !Equals
    - 'false'
    - !Ref EnvConfigDBARNAsString
  databaseADBEA118UseExistingResource: !Not
    - Condition: databaseADBEA118CreateNewResource
Metadata:
  EnvConfigParameters:
    EnvConfigVPCConfigAsString: VPC_Config
    EnvConfigDBARNAsString: DB_ARN